refactor(ppo): improved ppo agent, network, hyperparameters, and added main file with argument parser
kluge7/IDATT2502-NES-SM-ML pull request #29
Opened 2024-11-15 12:10 UTC by jenscaa

2024-11-15 18:13 UTC, jenscaa commented
Please merge asap

2024-11-15 20:46 UTC, kluge7 requested changes
fix the formatting

2024-11-15 21:20 UTC, kluge7 requested changes

2024-11-16 11:48 UTC, kluge7 approved these changes
LGTM

2024-11-16 11:48 UTC, merged